/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author JANCI
 */
public class calculadoraa extends javax.swing.JFrame {

        long a, b;
        long res;
        String tipo;
        long num;
        
    /**
     * Creates new form calculadoraa
     */
    public calculadoraa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(240, 390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btnmas = new javax.swing.JButton();
        btnmultiplicaion = new javax.swing.JButton();
        btnmenos = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btnporcentaje = new javax.swing.JButton();
        txta = new javax.swing.JTextField();
        txta1 = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 185, 50, 40));

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 185, 50, 40));

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 185, 50, 40));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 231, 50, 40));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 231, 50, 40));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 231, 50, 40));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 277, 50, 40));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 277, 50, 40));

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 277, 50, 40));

        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 323, 50, 40));

        btnpunto.setText(".");
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 323, 50, 40));

        btnigual.setText("=");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        getContentPane().add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 323, 50, 40));

        btnmas.setText("+");
        btnmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasActionPerformed(evt);
            }
        });
        getContentPane().add(btnmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 185, 50, 40));

        btnmultiplicaion.setText("*");
        btnmultiplicaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicaionActionPerformed(evt);
            }
        });
        getContentPane().add(btnmultiplicaion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 231, 50, 40));

        btnmenos.setText("-");
        btnmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenosActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 277, 50, 40));

        btndivision.setText("/");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btndivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 323, 50, 40));

        btnraiz.setText("rz");
        getContentPane().add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 141, 50, 38));

        jButton18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton18.setText("Off");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, 50, 38));

        btnporcentaje.setText("%");
        getContentPane().add(btnporcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 141, 50, 38));

        txta.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaActionPerformed(evt);
            }
        });
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaKeyTyped(evt);
            }
        });
        getContentPane().add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 218, 62));

        txta1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txta1.setEnabled(false);
        txta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txta1ActionPerformed(evt);
            }
        });
        txta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txta1KeyTyped(evt);
            }
        });
        getContentPane().add(txta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 218, 33));

        btnlimpiar.setText("C");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 141, 50, 38));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 4));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 340, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("1");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasActionPerformed
        num = Long.parseLong(txta.getText());
        txta1.setText(num + "+");
        txta.setText("");
        tipo="+";
    }//GEN-LAST:event_btnmasActionPerformed

    private void btnmultiplicaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicaionActionPerformed
        num = Long.parseLong(txta.getText());
        txta1.setText(num + "*");
        txta.setText("");
        tipo="*";
    }//GEN-LAST:event_btnmultiplicaionActionPerformed

    private void btnmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenosActionPerformed
        num = Long.parseLong(txta.getText());
        txta1.setText(num + "-");
        txta.setText("");
        tipo="-";
    }//GEN-LAST:event_btnmenosActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        num = Long.parseLong(txta.getText());
        txta1.setText(num + "/");
        txta.setText("");
        tipo="/";
    }//GEN-LAST:event_btndivisionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("2");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "2");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("3");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "3");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("4");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "4");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("5");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "5");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("6");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "6");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("7");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "7");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("8");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "8");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("9");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "9");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("0");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + "0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        try {
            if (txta.getText().equals("")) {
                txta.setText("0.");
            } else {
                a = Long.parseLong(txta.getText());
                txta.setText(a + ".");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero muy Grande \nERROR:" + e, "ERROR", 0);
        }
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void txtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaActionPerformed

    private void txtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyTyped
        Character car=evt.getKeyChar();
        if((!Character.isDigit(car))){
        evt.consume();
        }
    }//GEN-LAST:event_txtaKeyTyped

    private void txta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txta1ActionPerformed
        
    }//GEN-LAST:event_txta1ActionPerformed

    private void txta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txta1KeyTyped
        Character car=evt.getKeyChar();
        if((!Character.isDigit(car))&&(car!='.')){
        evt.consume();
        }
    }//GEN-LAST:event_txta1KeyTyped

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        if (tipo.equals("+")) {
            a = Long.parseLong(txta.getText());
            res = num+a;
            txta1.setText("");
            txta.setText("" + res);
        }
        if (tipo.equals("-")) {
            a = Long.parseLong(txta.getText());
            res = num-a;
            txta1.setText("");
            txta.setText("" + res);
        }
        if (tipo.equals("*")) {
            a = Long.parseLong(txta.getText());
            res = num*a;
            txta1.setText("");
            txta.setText("" + res);
        }
        if (tipo.equals("/")) {
            try{
            a = Long.parseLong(txta.getText());
            res = num/a;
            txta1.setText("");
            txta.setText("" + res);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error: "+e,"Error de resultado",0);
            }
        }
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txta.setText("");
        txta1.setText("");
        
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoraa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmas;
    private javax.swing.JButton btnmenos;
    private javax.swing.JButton btnmultiplicaion;
    private javax.swing.JButton btnporcentaje;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txta1;
    // End of variables declaration//GEN-END:variables
}
